# This is a basic workflow to help you get started with Actions

name: Project Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - master
      - dev

  pull_request:
    branches: 
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create env file
        run: |
          touch .env
          echo API_PORT=8000 >> .env
          echo API_HOST=0.0.0.0 >> .env
          echo SECRET_KEY=__secret__ >> .env
          echo ENVIRONMENT=DEBUG >> .env
          echo MYSQL_USER=root >> .env
          echo MYSQL_HOST=localhost >> .env
          echo MYSQL_PASSWORD=root >> .env
          echo MYSQL_PORT=3306 >> .env
          echo MYSQL_DATABASE=grocery_store >> .env
          cat .env

      - name: Set up database
        run: docker-compose up -d

      - name: Wait for db to spin up
        run: sleep 20

      - name: Run tests
        run: python -m unittest

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
